use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::error::{AppError, AppResult, ErrorKind};
use crate::git::ops::open_repo;

/// Directories we never descend into when looking for the user's Python files —
/// dependency/build/venv noise that would bury the real scripts.
const SKIP_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    "site-packages",
];

const MAX_FILES: usize = 400;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkflowInfo {
    /// File name, e.g. "hourly-report.yml".
    pub file: String,
}

/// Find the repository working directory for a path, erroring friendly if none.
fn workdir(repo_path: &Path) -> AppResult<PathBuf> {
    let repo = open_repo(repo_path)?;
    repo.workdir().map(|w| w.to_path_buf()).ok_or_else(|| {
        AppError::new(
            ErrorKind::NotARepo,
            "This repository has no working folder.",
        )
    })
}

/// List Python files in the repo (repo-relative, forward slashes), skipping
/// dependency/venv/build directories. Bounded so huge repos stay responsive.
pub fn list_python_files(repo_path: &Path) -> AppResult<Vec<String>> {
    let root = workdir(repo_path)?;
    let mut out = Vec::new();
    let mut stack = vec![root.clone()];

    while let Some(dir) = stack.pop() {
        if out.len() >= MAX_FILES {
            break;
        }
        let entries = match std::fs::read_dir(&dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let file_type = match entry.file_type() {
                Ok(t) => t,
                Err(_) => continue,
            };
            if file_type.is_dir() {
                let name = entry.file_name().to_string_lossy().to_string();
                if name.starts_with('.') || SKIP_DIRS.contains(&name.as_str()) {
                    continue;
                }
                stack.push(path);
            } else if path.extension().and_then(|e| e.to_str()) == Some("py") {
                if let Ok(rel) = path.strip_prefix(&root) {
                    out.push(rel.to_string_lossy().replace('\\', "/"));
                }
            }
        }
    }
    out.sort();
    Ok(out)
}

/// List existing workflow files under .github/workflows.
pub fn list_workflows(repo_path: &Path) -> AppResult<Vec<WorkflowInfo>> {
    let root = workdir(repo_path)?;
    let dir = root.join(".github").join("workflows");
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if name.ends_with(".yml") || name.ends_with(".yaml") {
                out.push(WorkflowInfo { file: name });
            }
        }
    }
    out.sort_by(|a, b| a.file.cmp(&b.file));
    Ok(out)
}

/// True if the repo has a top-level requirements.txt (drives whether the
/// generated workflow installs dependencies).
pub fn has_requirements(repo_path: &Path) -> AppResult<bool> {
    Ok(workdir(repo_path)?.join("requirements.txt").exists())
}

/// Turn a human title into a safe workflow file slug.
pub fn slug(name: &str) -> String {
    let mut s: String = name
        .trim()
        .to_lowercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    while s.contains("--") {
        s = s.replace("--", "-");
    }
    let s = s.trim_matches('-').to_string();
    if s.is_empty() {
        "scheduled-task".to_string()
    } else {
        s
    }
}

/// Generate a scheduled-Python workflow. Pure and testable — the UI passes a
/// cron string it built from a friendly schedule picker.
pub fn workflow_yaml(
    name: &str,
    python_path: &str,
    cron: &str,
    python_version: &str,
    install_requirements: bool,
) -> String {
    let install = if install_requirements {
        "\n      - run: pip install -r requirements.txt"
    } else {
        ""
    };
    format!(
        "# Generated by GitGlass. Runs {python_path} on a schedule.\n\
name: {name}\n\
\n\
on:\n\
\x20\x20schedule:\n\
\x20\x20\x20\x20- cron: \"{cron}\"\n\
\x20\x20workflow_dispatch: {{}}\n\
\n\
jobs:\n\
\x20\x20run:\n\
\x20\x20\x20\x20runs-on: ubuntu-latest\n\
\x20\x20\x20\x20steps:\n\
\x20\x20\x20\x20\x20\x20- uses: actions/checkout@v4\n\
\x20\x20\x20\x20\x20\x20- uses: actions/setup-python@v5\n\
\x20\x20\x20\x20\x20\x20\x20\x20with:\n\
\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20python-version: \"{python_version}\"{install}\n\
\x20\x20\x20\x20\x20\x20- run: python {python_path}\n"
    )
}

/// Write the generated workflow into .github/workflows/<slug>.yml and return the
/// absolute path so the UI can surface it for staging.
pub fn create_workflow(
    repo_path: &Path,
    name: &str,
    python_path: &str,
    cron: &str,
    python_version: &str,
    install_requirements: bool,
) -> AppResult<String> {
    if name.trim().is_empty() {
        return Err(AppError::new(
            ErrorKind::Git,
            "Please name this automation.",
        ));
    }
    if python_path.trim().is_empty() {
        return Err(AppError::new(
            ErrorKind::Git,
            "Please choose a Python file to run.",
        ));
    }
    let root = workdir(repo_path)?;
    let dir = root.join(".github").join("workflows");
    std::fs::create_dir_all(&dir)?;

    let file = dir.join(format!("{}.yml", slug(name)));
    let yaml = workflow_yaml(
        name,
        python_path,
        cron,
        python_version,
        install_requirements,
    );
    std::fs::write(&file, yaml)?;
    Ok(file.to_string_lossy().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slug_is_filesystem_safe() {
        assert_eq!(slug("Hourly Report!"), "hourly-report");
        assert_eq!(slug("  Nightly   Backup  "), "nightly-backup");
        assert_eq!(slug("weird@@@name"), "weird-name");
        assert_eq!(slug(""), "scheduled-task");
    }

    #[test]
    fn yaml_has_schedule_and_runs_the_file() {
        let y = workflow_yaml(
            "Hourly Report",
            "scripts/report.py",
            "0 * * * *",
            "3.12",
            false,
        );
        assert!(y.contains("cron: \"0 * * * *\""));
        assert!(y.contains("workflow_dispatch: {}"));
        assert!(y.contains("python-version: \"3.12\""));
        assert!(y.contains("- run: python scripts/report.py"));
        assert!(!y.contains("pip install"));
    }

    #[test]
    fn yaml_installs_requirements_when_requested() {
        let y = workflow_yaml("x", "a.py", "*/15 * * * *", "3.11", true);
        assert!(y.contains("pip install -r requirements.txt"));
    }

    #[test]
    fn yaml_indentation_is_valid_two_space() {
        // A couple of structural lines must have exact YAML indentation.
        let y = workflow_yaml("x", "a.py", "0 9 * * *", "3.12", false);
        assert!(y.contains("\n  schedule:\n"));
        assert!(y.contains("\n    - cron:"));
        assert!(y.contains("\n      - uses: actions/checkout@v4\n"));
        assert!(y.contains("\n        with:\n"));
        assert!(y.contains("\n          python-version:"));
    }
}
